language: java

jdk:
  - oraclejdk8

dist: trusty

addons:
  apt:
    packages:
      - oracle-java8-installer
      
notifications:
  email: false
  
ignore:
  - "doc/"
  - "*.md"
  - "*.txt"

install: true
   
