#include <stdio.h>
#include <stdlib.h>
#include <jni.h>

#include "nativeCode.h" // generated by javah via maven-native-plugin
#include "opencv2/core/core.hpp"

#include <iostream>


using namespace std;
using namespace cv;

JNIEXPORT void JNICALL Java_cc0_JniExample_helloNative
  (JNIEnv * env, jobject obj)
{
    puts("Hello from C++!");
    
    puts("CV Constant usage example:");
	int value = CV_64F;
	cout << "CV_64F = " << value << endl;
}

