#include <stdio.h>
#include <stdlib.h>
#include <iostream>

#include "nativeCode.h" // generated by javah via maven-native-plugin

#include "opencv2/core/core.hpp"
#include "JwMat.h"

using namespace std;
using namespace cv;

JNIEXPORT void JNICALL Java_cc0_NativeExample_init
  (JNIEnv* env, jobject obj)
{
  cout << "Java_cc0_NativeExample_init START" << endl;
  JwMat mat(env);
  cout << "Java_cc0_NativeExample_init END" << endl;
}


JNIEXPORT void JNICALL Java_cc0_NativeExample_process
  (JNIEnv* env, jobject obj,
   jobject matobj, jint frameId)
{
  cout << "Java_cc0_NativeExample_process CALLED " << frameId << endl;
}

